
# This file is automatically generated, you probably don't want to edit this

t2testOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "t2testOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            xbar1 = NULL,
            s1 = NULL,
            n1 = NULL,
            xbar2 = NULL,
            s2 = NULL,
            n2 = NULL,
            ha = "notequal",
            showci = FALSE,
            cilevel = 95, ...) {

            super$initialize(
                package="ctools",
                name="t2test",
                requiresData=FALSE,
                ...)

            private$..xbar1 <- jmvcore::OptionNumber$new(
                "xbar1",
                xbar1)
            private$..s1 <- jmvcore::OptionNumber$new(
                "s1",
                s1)
            private$..n1 <- jmvcore::OptionInteger$new(
                "n1",
                n1)
            private$..xbar2 <- jmvcore::OptionNumber$new(
                "xbar2",
                xbar2)
            private$..s2 <- jmvcore::OptionNumber$new(
                "s2",
                s2)
            private$..n2 <- jmvcore::OptionInteger$new(
                "n2",
                n2)
            private$..ha <- jmvcore::OptionList$new(
                "ha",
                ha,
                options=list(
                    "notequal",
                    "lessthan",
                    "greaterthan"),
                default="notequal")
            private$..showci <- jmvcore::OptionBool$new(
                "showci",
                showci,
                default=FALSE)
            private$..cilevel <- jmvcore::OptionNumber$new(
                "cilevel",
                cilevel,
                default=95,
                min=50,
                max=99.5)

            self$.addOption(private$..xbar1)
            self$.addOption(private$..s1)
            self$.addOption(private$..n1)
            self$.addOption(private$..xbar2)
            self$.addOption(private$..s2)
            self$.addOption(private$..n2)
            self$.addOption(private$..ha)
            self$.addOption(private$..showci)
            self$.addOption(private$..cilevel)
        }),
    active = list(
        xbar1 = function() private$..xbar1$value,
        s1 = function() private$..s1$value,
        n1 = function() private$..n1$value,
        xbar2 = function() private$..xbar2$value,
        s2 = function() private$..s2$value,
        n2 = function() private$..n2$value,
        ha = function() private$..ha$value,
        showci = function() private$..showci$value,
        cilevel = function() private$..cilevel$value),
    private = list(
        ..xbar1 = NA,
        ..s1 = NA,
        ..n1 = NA,
        ..xbar2 = NA,
        ..s2 = NA,
        ..n2 = NA,
        ..ha = NA,
        ..showci = NA,
        ..cilevel = NA)
)

t2testResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "t2testResults",
    inherit = jmvcore::Group,
    active = list(
        restab = function() private$.items[["restab"]],
        conftab = function() private$.items[["conftab"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Test for a Difference in Means")
            self$add(jmvcore::Table$new(
                options=options,
                name="restab",
                title="Hypothesis Test",
                rows=1,
                columns=list(
                    list(
                        `name`="diff_xbar", 
                        `type`="number", 
                        `title`="Difference in Sample Means"),
                    list(
                        `name`="tstat", 
                        `type`="number", 
                        `title`="t"),
                    list(
                        `name`="se", 
                        `type`="number", 
                        `title`="SE"),
                    list(
                        `name`="p", 
                        `type`="number", 
                        `title`="p-value", 
                        `format`="zto,pvalue")),
                clearWith=list(
                    "xbar1",
                    "xbar2",
                    "s1",
                    "s2",
                    "n1",
                    "n2",
                    "ha",
                    "showci")))
            self$add(jmvcore::Table$new(
                options=options,
                name="conftab",
                title="Confidence Interval",
                visible="(showci)",
                rows=1,
                columns=list(
                    list(
                        `name`="lvl", 
                        `type`="text", 
                        `title`=""),
                    list(
                        `name`="lwr", 
                        `type`="number", 
                        `title`="Lower", 
                        `format`="zto, pvalue"),
                    list(
                        `name`="uppr", 
                        `type`="number", 
                        `title`="Upper", 
                        `format`="zto, pvalue")),
                clearWith=list(
                    "xbar1",
                    "xbar2",
                    "s1",
                    "s2",
                    "n1",
                    "n2",
                    "ha",
                    "showci",
                    "cilevel")))}))

t2testBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "t2testBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "ctools",
                name = "t2test",
                version = c(1,0,0),
                options = options,
                results = t2testResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Test for a Difference in Means
#'
#' 
#' @param xbar1 .
#' @param s1 .
#' @param n1 .
#' @param xbar2 .
#' @param s2 .
#' @param n2 .
#' @param ha .
#' @param showci .
#' @param cilevel .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$restab} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$conftab} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$restab$asDF}
#'
#' \code{as.data.frame(results$restab)}
#'
#' @export
t2test <- function(
    xbar1,
    s1,
    n1,
    xbar2,
    s2,
    n2,
    ha = "notequal",
    showci = FALSE,
    cilevel = 95) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("t2test requires jmvcore to be installed (restart may be required)")


    options <- t2testOptions$new(
        xbar1 = xbar1,
        s1 = s1,
        n1 = n1,
        xbar2 = xbar2,
        s2 = s2,
        n2 = n2,
        ha = ha,
        showci = showci,
        cilevel = cilevel)

    analysis <- t2testClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

