
# This file is automatically generated, you probably don't want to edit this

ttestOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ttestOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            xbar = NULL,
            s = NULL,
            n = NULL,
            mu0 = NULL,
            ha = "notequal",
            showci = FALSE,
            cilevel = 95, ...) {

            super$initialize(
                package="ctools",
                name="ttest",
                requiresData=FALSE,
                ...)

            private$..xbar <- jmvcore::OptionNumber$new(
                "xbar",
                xbar)
            private$..s <- jmvcore::OptionNumber$new(
                "s",
                s)
            private$..n <- jmvcore::OptionInteger$new(
                "n",
                n)
            private$..mu0 <- jmvcore::OptionNumber$new(
                "mu0",
                mu0)
            private$..ha <- jmvcore::OptionList$new(
                "ha",
                ha,
                options=list(
                    "notequal",
                    "lessthan",
                    "greaterthan"),
                default="notequal")
            private$..showci <- jmvcore::OptionBool$new(
                "showci",
                showci,
                default=FALSE)
            private$..cilevel <- jmvcore::OptionNumber$new(
                "cilevel",
                cilevel,
                default=95,
                min=50,
                max=99.5)

            self$.addOption(private$..xbar)
            self$.addOption(private$..s)
            self$.addOption(private$..n)
            self$.addOption(private$..mu0)
            self$.addOption(private$..ha)
            self$.addOption(private$..showci)
            self$.addOption(private$..cilevel)
        }),
    active = list(
        xbar = function() private$..xbar$value,
        s = function() private$..s$value,
        n = function() private$..n$value,
        mu0 = function() private$..mu0$value,
        ha = function() private$..ha$value,
        showci = function() private$..showci$value,
        cilevel = function() private$..cilevel$value),
    private = list(
        ..xbar = NA,
        ..s = NA,
        ..n = NA,
        ..mu0 = NA,
        ..ha = NA,
        ..showci = NA,
        ..cilevel = NA)
)

ttestResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ttestResults",
    inherit = jmvcore::Group,
    active = list(
        restab = function() private$.items[["restab"]],
        conftab = function() private$.items[["conftab"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Test for a Single or Paired Mean")
            self$add(jmvcore::Table$new(
                options=options,
                name="restab",
                title="Hypothesis Test",
                rows=1,
                columns=list(
                    list(
                        `name`="xbar", 
                        `type`="number", 
                        `title`="Sample Mean"),
                    list(
                        `name`="tstat", 
                        `type`="number", 
                        `title`="t"),
                    list(
                        `name`="se", 
                        `type`="number", 
                        `title`="SE"),
                    list(
                        `name`="p", 
                        `type`="number", 
                        `title`="p-value", 
                        `format`="zto,pvalue")),
                clearWith=list(
                    "xbar",
                    "s",
                    "mu0",
                    "n",
                    "ha",
                    "showci")))
            self$add(jmvcore::Table$new(
                options=options,
                name="conftab",
                title="Confidence Interval",
                visible="(showci)",
                rows=1,
                columns=list(
                    list(
                        `name`="lvl", 
                        `type`="text", 
                        `title`=""),
                    list(
                        `name`="lwr", 
                        `type`="number", 
                        `title`="Lower", 
                        `format`="zto, pvalue"),
                    list(
                        `name`="uppr", 
                        `type`="number", 
                        `title`="Upper", 
                        `format`="zto, pvalue")),
                clearWith=list(
                    "xbar",
                    "s",
                    "mu0",
                    "n",
                    "ha",
                    "showci",
                    "cilevel")))}))

ttestBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ttestBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "ctools",
                name = "ttest",
                version = c(1,0,0),
                options = options,
                results = ttestResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Test for a Single or Paired Mean
#'
#' 
#' @param xbar .
#' @param s .
#' @param n .
#' @param mu0 .
#' @param ha .
#' @param showci .
#' @param cilevel .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$restab} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$conftab} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$restab$asDF}
#'
#' \code{as.data.frame(results$restab)}
#'
#' @export
ttest <- function(
    xbar,
    s,
    n,
    mu0,
    ha = "notequal",
    showci = FALSE,
    cilevel = 95) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("ttest requires jmvcore to be installed (restart may be required)")


    options <- ttestOptions$new(
        xbar = xbar,
        s = s,
        n = n,
        mu0 = mu0,
        ha = ha,
        showci = showci,
        cilevel = cilevel)

    analysis <- ttestClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

