
# This file is automatically generated, you probably don't want to edit this

z2testOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "z2testOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            c1 = NULL,
            c2 = NULL,
            n1 = NULL,
            n2 = NULL,
            p0 = 0,
            ha = "notequal",
            showci = FALSE,
            cilevel = 95, ...) {

            super$initialize(
                package="ctools",
                name="z2test",
                requiresData=FALSE,
                ...)

            private$..c1 <- jmvcore::OptionNumber$new(
                "c1",
                c1)
            private$..c2 <- jmvcore::OptionNumber$new(
                "c2",
                c2)
            private$..n1 <- jmvcore::OptionInteger$new(
                "n1",
                n1)
            private$..n2 <- jmvcore::OptionInteger$new(
                "n2",
                n2)
            private$..p0 <- jmvcore::OptionNumber$new(
                "p0",
                p0,
                default=0)
            private$..ha <- jmvcore::OptionList$new(
                "ha",
                ha,
                options=list(
                    "notequal",
                    "lessthan",
                    "greaterthan"),
                default="notequal")
            private$..showci <- jmvcore::OptionBool$new(
                "showci",
                showci,
                default=FALSE)
            private$..cilevel <- jmvcore::OptionNumber$new(
                "cilevel",
                cilevel,
                default=95,
                min=50,
                max=99.5)

            self$.addOption(private$..c1)
            self$.addOption(private$..c2)
            self$.addOption(private$..n1)
            self$.addOption(private$..n2)
            self$.addOption(private$..p0)
            self$.addOption(private$..ha)
            self$.addOption(private$..showci)
            self$.addOption(private$..cilevel)
        }),
    active = list(
        c1 = function() private$..c1$value,
        c2 = function() private$..c2$value,
        n1 = function() private$..n1$value,
        n2 = function() private$..n2$value,
        p0 = function() private$..p0$value,
        ha = function() private$..ha$value,
        showci = function() private$..showci$value,
        cilevel = function() private$..cilevel$value),
    private = list(
        ..c1 = NA,
        ..c2 = NA,
        ..n1 = NA,
        ..n2 = NA,
        ..p0 = NA,
        ..ha = NA,
        ..showci = NA,
        ..cilevel = NA)
)

z2testResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "z2testResults",
    inherit = jmvcore::Group,
    active = list(
        restab = function() private$.items[["restab"]],
        conftab = function() private$.items[["conftab"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Difference in Proportions Test")
            self$add(jmvcore::Table$new(
                options=options,
                name="restab",
                title="Hypothesis Test",
                rows=1,
                columns=list(
                    list(
                        `name`="diff_phat", 
                        `type`="number", 
                        `title`="Difference in Proportions"),
                    list(
                        `name`="z", 
                        `type`="number"),
                    list(
                        `name`="se", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `type`="number", 
                        `title`="p-value", 
                        `format`="zto,pvalue")),
                clearWith=list(
                    "phat1",
                    "phat2",
                    "p0",
                    "n",
                    "ha",
                    "showci")))
            self$add(jmvcore::Table$new(
                options=options,
                name="conftab",
                title="Confidence Interval",
                visible="(showci)",
                rows=1,
                columns=list(
                    list(
                        `name`="lvl", 
                        `type`="text", 
                        `title`=""),
                    list(
                        `name`="lwr", 
                        `type`="number", 
                        `title`="Lower"),
                    list(
                        `name`="uppr", 
                        `type`="number", 
                        `title`="Upper")),
                clearWith=list(
                    "phat1",
                    "phat2",
                    "p0",
                    "n",
                    "ha",
                    "showci",
                    "cilevel")))}))

z2testBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "z2testBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "ctools",
                name = "z2test",
                version = c(1,0,0),
                options = options,
                results = z2testResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Test for a Difference in Proportions
#'
#' 
#' @param c1 .
#' @param c2 .
#' @param n1 .
#' @param n2 .
#' @param p0 .
#' @param ha .
#' @param showci .
#' @param cilevel .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$restab} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$conftab} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$restab$asDF}
#'
#' \code{as.data.frame(results$restab)}
#'
#' @export
z2test <- function(
    c1,
    c2,
    n1,
    n2,
    p0 = 0,
    ha = "notequal",
    showci = FALSE,
    cilevel = 95) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("z2test requires jmvcore to be installed (restart may be required)")


    options <- z2testOptions$new(
        c1 = c1,
        c2 = c2,
        n1 = n1,
        n2 = n2,
        p0 = p0,
        ha = ha,
        showci = showci,
        cilevel = cilevel)

    analysis <- z2testClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

