
# This file is automatically generated, you probably don't want to edit this

ztestOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ztestOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            phat = NULL,
            p0 = 0.5,
            n = NULL,
            ha = "notequal", ...) {

            super$initialize(
                package="ctools",
                name="ztest",
                requiresData=FALSE,
                ...)

            private$..phat <- jmvcore::OptionNumber$new(
                "phat",
                phat)
            private$..p0 <- jmvcore::OptionNumber$new(
                "p0",
                p0,
                default=0.5)
            private$..n <- jmvcore::OptionInteger$new(
                "n",
                n)
            private$..ha <- jmvcore::OptionList$new(
                "ha",
                ha,
                options=list(
                    "notequal",
                    "lessthan",
                    "greaterthan"),
                default="notequal")

            self$.addOption(private$..phat)
            self$.addOption(private$..p0)
            self$.addOption(private$..n)
            self$.addOption(private$..ha)
        }),
    active = list(
        phat = function() private$..phat$value,
        p0 = function() private$..p0$value,
        n = function() private$..n$value,
        ha = function() private$..ha$value),
    private = list(
        ..phat = NA,
        ..p0 = NA,
        ..n = NA,
        ..ha = NA)
)

ztestResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ztestResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="One-Sample Z-Test")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="One-Sample Z-Test"))}))

ztestBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ztestBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "ctools",
                name = "ztest",
                version = c(1,0,0),
                options = options,
                results = ztestResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' One-Sample Z-Test (Summary)
#'
#' 
#' @param phat .
#' @param p0 .
#' @param n .
#' @param ha .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
ztest <- function(
    phat,
    p0 = 0.5,
    n,
    ha = "notequal") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("ztest requires jmvcore to be installed (restart may be required)")


    options <- ztestOptions$new(
        phat = phat,
        p0 = p0,
        n = n,
        ha = ha)

    analysis <- ztestClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

