
# This file is automatically generated, you probably don't want to edit this

ztestOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ztestOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            phat = NULL,
            n = NULL,
            p0 = NULL,
            ha = "notequal",
            showci = FALSE,
            cilevel = 95, ...) {

            super$initialize(
                package="ctools",
                name="ztest",
                requiresData=FALSE,
                ...)

            private$..phat <- jmvcore::OptionNumber$new(
                "phat",
                phat)
            private$..n <- jmvcore::OptionInteger$new(
                "n",
                n)
            private$..p0 <- jmvcore::OptionNumber$new(
                "p0",
                p0)
            private$..ha <- jmvcore::OptionList$new(
                "ha",
                ha,
                options=list(
                    "notequal",
                    "lessthan",
                    "greaterthan"),
                default="notequal")
            private$..showci <- jmvcore::OptionBool$new(
                "showci",
                showci,
                default=FALSE)
            private$..cilevel <- jmvcore::OptionNumber$new(
                "cilevel",
                cilevel,
                default=95,
                min=50,
                max=99.5)

            self$.addOption(private$..phat)
            self$.addOption(private$..n)
            self$.addOption(private$..p0)
            self$.addOption(private$..ha)
            self$.addOption(private$..showci)
            self$.addOption(private$..cilevel)
        }),
    active = list(
        phat = function() private$..phat$value,
        n = function() private$..n$value,
        p0 = function() private$..p0$value,
        ha = function() private$..ha$value,
        showci = function() private$..showci$value,
        cilevel = function() private$..cilevel$value),
    private = list(
        ..phat = NA,
        ..n = NA,
        ..p0 = NA,
        ..ha = NA,
        ..showci = NA,
        ..cilevel = NA)
)

ztestResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ztestResults",
    inherit = jmvcore::Group,
    active = list(
        restab = function() private$.items[["restab"]],
        conftab = function() private$.items[["conftab"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Test for a Single Proportion")
            self$add(jmvcore::Table$new(
                options=options,
                name="restab",
                title="Hypothesis Test",
                rows=1,
                columns=list(
                    list(
                        `name`="phat", 
                        `type`="number", 
                        `title`="Sample Proportion"),
                    list(
                        `name`="z", 
                        `type`="number"),
                    list(
                        `name`="se", 
                        `type`="number", 
                        `title`="SE"),
                    list(
                        `name`="p", 
                        `type`="number", 
                        `title`="p-value", 
                        `format`="zto,pvalue")),
                clearWith=list(
                    "phat",
                    "p0",
                    "n",
                    "ha",
                    "showci")))
            self$add(jmvcore::Table$new(
                options=options,
                name="conftab",
                title="Confidence Interval",
                visible="(showci)",
                rows=1,
                columns=list(
                    list(
                        `name`="lvl", 
                        `type`="text", 
                        `title`=""),
                    list(
                        `name`="lwr", 
                        `type`="number", 
                        `title`="Lower", 
                        `format`="zto, pvalue"),
                    list(
                        `name`="uppr", 
                        `type`="number", 
                        `title`="Upper", 
                        `format`="zto, pvalue")),
                clearWith=list(
                    "phat",
                    "p0",
                    "n",
                    "ha",
                    "showci",
                    "cilevel")))}))

ztestBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ztestBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "ctools",
                name = "ztest",
                version = c(1,0,0),
                options = options,
                results = ztestResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Test for a Single Proportion
#'
#' 
#' @param phat .
#' @param n .
#' @param p0 .
#' @param ha .
#' @param showci .
#' @param cilevel .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$restab} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$conftab} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$restab$asDF}
#'
#' \code{as.data.frame(results$restab)}
#'
#' @export
ztest <- function(
    phat,
    n,
    p0,
    ha = "notequal",
    showci = FALSE,
    cilevel = 95) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("ztest requires jmvcore to be installed (restart may be required)")


    options <- ztestOptions$new(
        phat = phat,
        n = n,
        p0 = p0,
        ha = ha,
        showci = showci,
        cilevel = cilevel)

    analysis <- ztestClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

