
# This file is automatically generated, you probably don't want to edit this

ztest1dataOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ztest1dataOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            var = NULL,
            p0 = 0.5,
            ha = "notequal", ...) {

            super$initialize(
                package="ctools",
                name="ztest1data",
                requiresData=TRUE,
                ...)

            private$..var <- jmvcore::OptionVariable$new(
                "var",
                var)
            private$..p0 <- jmvcore::OptionNumber$new(
                "p0",
                p0,
                default=0.5)
            private$..ha <- jmvcore::OptionList$new(
                "ha",
                ha,
                options=list(
                    "notequal",
                    "lessthan",
                    "greaterthan"),
                default="notequal")

            self$.addOption(private$..var)
            self$.addOption(private$..p0)
            self$.addOption(private$..ha)
        }),
    active = list(
        var = function() private$..var$value,
        p0 = function() private$..p0$value,
        ha = function() private$..ha$value),
    private = list(
        ..var = NA,
        ..p0 = NA,
        ..ha = NA)
)

ztest1dataResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ztest1dataResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="One-Sample Z-Test (Data)")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="One-Sample Z-Test (Data)"))}))

ztest1dataBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ztest1dataBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "ctools",
                name = "ztest1data",
                version = c(1,0,0),
                options = options,
                results = ztest1dataResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' One-Sample Z-Test (Data)
#'
#' 
#' @param data .
#' @param var .
#' @param p0 .
#' @param ha .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
ztest1data <- function(
    data,
    var,
    p0 = 0.5,
    ha = "notequal") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("ztest1data requires jmvcore to be installed (restart may be required)")

    if ( ! missing(var)) var <- jmvcore::resolveQuo(jmvcore::enquo(var))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(var), var, NULL))


    options <- ztest1dataOptions$new(
        var = var,
        p0 = p0,
        ha = ha)

    analysis <- ztest1dataClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

